[ui]
lang = "zh-CN"
theme = "Light"

[storage]
pending_path = "C:\\Users\\chika\\Downloads\\AnimeRepository"
repository_path = "C:\\Users\\chika\\Videos\\AnimeRepository"

[network]
use_proxy = false
