name: "Release CI"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use

      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          TAURI_PRIVATE_KEY: "${{ secrets.TAURI_PRIVATE_KEY }}"
          TAURI_KEY_PASSWORD: "${{ secrets.TAURI_KEY_PASSWORD }}"
        with:
          tagName: v__VERSION__
          releaseName: "Anime Repository v__VERSION__"
          releaseBody: "More new features are now supported."
          releaseDraft: false
          prerelease: true

      - name: Portable Bundle
        if: matrix.platform == 'windows-latest'
        # rebuild with env settings
        run: |
          yarn tauri build
          yarn run portable
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          TAURI_PRIVATE_KEY: "${{ secrets.TAURI_PRIVATE_KEY }}"
          TAURI_KEY_PASSWORD: "${{ secrets.TAURI_KEY_PASSWORD }}"

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    needs: [build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })

  release-update:
    needs: [build-tauri, publish-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get yarn cache dir path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Yarn Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn install
        run: yarn install

      - name: Release updater file
        run: yarn run updater
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
